### ISSUE TITLE
Validazione XML (Perl)

### ISSUE THREAD

**Issue by Jefffrey** [TecnologieWeb/progetto#10]
Vedere se vale la pena controllare la validità del file XML dopo ogni modifica.

**Comment by Jefffrey** [comment]
Questo mi sembra che sia semplice come chiamare `$doc->valid()` o giù di li, ad ogni modifica.

**Comment by jacopocav** [comment]
La funzione di validazione l'ho fatta, ma non so se ha senso validare ad ogni modifica, visto che il programma è fatto in modo da creare xml sempre valido

**Comment by Jefffrey** [comment]
Il fatto è che con le nuovi funzioni questa cosa è molto semplice. Basta aggiungere la validazione in `edit_xml`.
