### ISSUE TITLE
Sicurezza

### ISSUE THREAD

**Issue by Jefffrey** [TecnologieWeb/progetto#11]
Forse è il caso di fare l'escaping di caratteri XML da input e prevenire attacchi XSS.

**Comment by jacopocav** [comment]
Ho visto che durante l'input l'escape dei caratteri avviene automaticamente: '<' diventa '&lt;' e così via.
Il problema è nell'output da xml. Questo si può risolvere usando HTML::Entities e invocando encode_entities(out) sull'output su cui fare escaping. il problema è capire se questo modulo è presente nelle macchine del laboratorio.

**Comment by Jefffrey** [comment]
Non sembra: http://docenti.math.unipd.it/gaggi/tecweb/librerie.html
