### ISSUE TITLE
Link circolari su login e registrazione

### ISSUE THREAD

**Issue by jacopocav** [TecnologieWeb/progetto#12]
Bisogna fare in modo che i link di login e registrazione siano non cliccabili quando ci si trova nelle rispettive pagine.

**Comment by Jefffrey** [comment]
Risolto anche questo da jacopo.

**Comment by jacopocav** [comment]
Purtroppo no, se non si è autenticati e si entra nella pagina di login è ancora possibile cliccare il link al login

**Comment by Jefffrey** [comment]
@jacopocav Adesso dovrebbe essere risolto. No?
