### ISSUE TITLE
Forse utilizzare moduli invece che require?

### ISSUE THREAD

**Issue by Jefffrey** [TecnologieWeb/progetto#18]
Non so se cambia qualcosa ma forse bisognerà cambiare i file `.pl` in `.pm` e utilizzare `use` invece che `require`. Non importante comunque.

**Comment by jacopocav** [comment]
Si, mi sembra una cosa migliore, in quanto 'use' viene valutato a compile time, invece 'require' viene valutato in runtime. Questo crea problemi se i file .cgi li organizziamo in sottocartelle (ci vorrebbe un require diverso per ogni file)
