### ISSUE TITLE
Definire funzioni esplicite per errori e/o messaggi di successo

### ISSUE THREAD

**Issue by Jefffrey** [TecnologieWeb/progetto#22]
E' meglio definire esplicite funzioni in `html.pl` che stampino messaggi di errore o di successo. Un esempio è:

```perl
print error("Non hai i permessi necessari");
```

invece che:

```perl
print content(sub {
    return 'Non hai i permessi necessari';
});
```

In questo modo possiamo modificare questo tipo di messaggi in un posto solo (per aggiungere stili o definizioni HTML di markup).

**Comment by jacopocav** [comment]
Dove dovremmo usarla un'eventuale funzione di questo tipo?

**Comment by Jefffrey** [comment]
Tipo nelle pagine admin dove scriviamo che non ha i permessi. E per quanto riguarda `print message(...)` nelle pagine dove stampiamo solo che qualcosa è avvenuta con successo. Tipo la registrazione:

```perl
print content(sub {
    return p('Registrazione avvenuta con successo! Ora puoi accedere al tuo nuovo account!');
});
```

diventa:

```perl
print message('Registrazione avvenuta con successo! Ora puoi accedere al tuo nuovo account!');
```
