### ISSUE TITLE
Usare un'altra definizione per il numero di telefono

### ISSUE THREAD

**Issue by Jefffrey** [TecnologieWeb/progetto#24]
Forse è meglio utilizzare questa definizione invece che la mia:

![screen shot 2015-01-26 at 21 43 09](https://cloud.githubusercontent.com/assets/733227/5908352/f7339c88-a5a6-11e4-8b3a-d3326dee988b.png)

Forse senza i trattini e permettendo sia `0039` che `+39`.

**Comment by jacopocav** [comment]
Non mi sembra ci sia tanta differenza, a parte che questa non accetta i numeri di cellulare.
Per restringere i numeri possibili si potrebbe usare /(\+39|0039)?(0|3)[0-9]+/

**Comment by Jefffrey** [comment]
Quello accetterebbe +3932 che non è un numero di cellulare. La mia non tiene in considerazione `0039` e da una limitazione massima della lunghezza dei numeri che è abbastanza arbitraria (mi sembra di aver letto da qualche parte che gli ultimi numeri dati avevano 12 cifre e il minimo fosse 7.

Propongo di aggiungere `0039` come possibilità e semplicemente definirle un numero come un prefisso di 3 cifre e un tot di altri numeri. Specificamente:

`((+|00)39)?[0-9]{3}[0-9]+`

O qualcosa in quella direzione (Non credo che si possano annidare quelle parentesi tonde).

**Comment by jacopocav** [comment]
Basta mettere '\' davanti al '+' e la tua regex è apposto. Comunque per me è ok cambiarla come dici tu
