### ISSUE TITLE
Pulsante "Mi Piace/Non Mi Piace" per i prodotti della galleria

### ISSUE THREAD

**Issue by jacopocav** [TecnologieWeb/progetto#26]
All'inizio si parlava anche di una cosa simile, se volete si può fare

**Comment by Jefffrey** [comment]
In ordine di priorità ci andrebbero gli ordini. Secondo me riusciamo tranquillamente a fare tutta la parte degli ordini in massimo 4 giorni, e fornirebbe un sito molto più completo dal punto di vista dell'utente. Ormai la parte più difficile l'abbiamo fatta: capire l'ambiente Perl e XMLSchema.

Più cose mettiamo e meno è la probabilità che ci faccia fare l'orale. Siamo anche in stra anticipo (vedi data di consegna 9 febbraio).

**Comment by jacopocav** [comment]
Direi che visto che stiamo facendo gli ordini questa funzionalità non ha più tanto senso
