### ISSUE TITLE
[CSS] Sistemare form aggiunta feedback

### ISSUE THREAD

**Issue by jacopocav** [TecnologieWeb/progetto#27]

**Comment by jacopocav** [comment]
scusa luca, ma le stelle messe in orizzontale non si vedono bene in finestre strette, e le label sono troppo a sinistra secondo me. Bisognerebbe farlo simile al form di registrazione, con le stelle disposte in verticale e tutto centrato

**Comment by luhahaha** [comment]
Oooook;)
