### ISSUE TITLE
Forse ordinare per ID i prodotti in galleria

### ISSUE THREAD

**Issue by Jefffrey** [TecnologieWeb/progetto#29]
Non sono sicuro al momento se gli ordini vengono ordinati in base all'id, questo è per ricordarmi di controllare.

**Comment by Jefffrey** [comment]
Si può fare. Bisogna riordinare prima il file xml.pm.

**Comment by jacopocav** [comment]
Chiuso con d7118a6d832e71d0e24be7d9c3f31834d9a42539
