### ISSUE TITLE
Decidere stile formattazione

### ISSUE THREAD

**Issue by Jefffrey** [TecnologieWeb/progetto#31]
Ci sono alcune inconsistenze con lo stile del codice mio e di Jacopo. Tipo io uso `func(x, y)`, lui usa `func( x, y )`. Dobbiamo decidere quale utilizzare ed uniformarci

**Comment by jacopocav** [comment]
A me viene quella formattazione perchè uso perltidy, che è uno strumento automatico che formatta il codice rendendolo più leggibile. In realtà non sono scrivo normalmente così

**Comment by Jefffrey** [comment]
> In realtà non sono scrivo normalmente così

?

**Comment by jacopocav** [comment]
lol. Allora usi anche tu perltidy?
