### ISSUE TITLE
Utilizzare tende a veneziana per XMLSchema

### ISSUE THREAD

**Issue by Jefffrey** [TecnologieWeb/progetto#32]
Sarebbe meglio utilizzare tende a veneziana (root element globale + elementi e tipi nello spazio dell'elemento root). Questo potrebbe anche risolverci il problema del namespace.

**Comment by jacopocav** [comment]
Ormai abbiamo utilizzato $xmlns ovunque, direi che è meglio lasciare così

**Comment by Jefffrey** [comment]
Sono sicuro che nella notte dell'8 febbraio,  annoiato, farò questa modifica rampante e romperò tutto.
