### ISSUE TITLE
Ordinare i commenti per voto e poi per data

### ISSUE THREAD

**Issue by Jefffrey** [TecnologieWeb/progetto#34]
I commenti migliori vanno in alto e quelli peggiori in basso (così non vengono visti). Oppure ordinarli in base alla data.

**Comment by jacopocav** [comment]
Questo può essere molto utile https://www.stormconsultancy.co.uk/blog/development/code-snippets/perl-sorting-an-array-of-hashes/

**Comment by jacopocav** [comment]
Risolto con d7118a6d832e71d0e24be7d9c3f31834d9a42539.
