### ISSUE TITLE
Problema lettura xml

### ISSUE THREAD

**Issue by jacopocav** [TecnologieWeb/progetto#4]
lo script cgi non riesce a controllare se esiste già un utente con una determinata mail o username.
Ho provato a scrivere le espressioni xpath su questo sito:
http://www.xpathtester.com/xpath
e ho visto che funzionano solo se rimuoviamo tutta la parte dei namespace dal file xml. Che si fa?

**Comment by Jefffrey** [comment]
Si si avevo già notato. Infatti ho eliminato il namespace `ns` da tutti i file XML. Non serviva a nulla in ogni caso.

**Comment by Jefffrey** [comment]
Questo è stato risolto.
