### ISSUE TITLE
Ordine degli ordini

### ISSUE THREAD

**Issue by Jefffrey** [TecnologieWeb/progetto#41]
L'ordine degli ordini sembra buggato. Dovrebbero essere ordinati in base al `order_date`, ma io li vedo così:

![screen shot 2015-02-03 at 21 47 45](https://cloud.githubusercontent.com/assets/733227/6029112/9aadec5e-abee-11e4-8d7b-527340d562e5.png)

Era così anche prima dell'aggiunta del parametro `$order_by` in `get_elements`.

**Comment by jacopocav** [comment]
A me prima funzionava normalmente
Il problema che ho visto adesso è che l'ordinamento viene sempre fatto in maniera decrescente. Bisognerebbe o aggiungere un altro campo che indica se l'ordinamento va fatto in maniera ascendente o discendente, o trovare un modo per passare una funzione sort come parametro

**Comment by Jefffrey** [comment]
Ho visto usare `-campo` e `campo` per definite il decrescente/crescente. Ci penso io in un paio d'ore.
