### ISSUE TITLE
Validare tutte le pagine prima di consegnare

### ISSUE THREAD

**Issue by jacopocav** [TecnologieWeb/progetto#43]
- [x] home.cgi
- [x] products.cgi (non autenticato)
- [x] products.cgi (cliente)
- [x] products.cgi (admin)
- [x] orders.cgi
- [x] feedbacks.cgi
- [x] contacts.cgi
- [x] login.cgi
- [x] logout.cgi
- [x] registration.cgi
- [x] settings.cgi
- [x] add_product.cgi
- [x] remove_product.cgi
- [x] edit_product.cgi
- [x] add_feedback.cgi
- [x] remove_feedback.cgi
- [x] add_order.cgi
- [x] remove_order.cgi
- [x] stile.css

**Comment by jacopocav** [comment]
Validate home, galleria e commenti, mancano le altre

**Comment by jacopocav** [comment]
Validata Ordini

**Comment by jacopocav** [comment]
Validato CSS (anche se va ricontrollato per bene ancora)

**Comment by jacopocav** [comment]
Validato Registrazione

**Comment by jacopocav** [comment]
Validato Contatti, Login e Registrazione

**Comment by Jefffrey** [comment]
La pagina `gallery.cgi` è diventata `products.cgi`. Ci sono state modifiche di titoli e descrizioni. Nel dubbio è meglio validarla.

**Comment by Jefffrey** [comment]
- [x] home.cgi
- [x] contacts.cgi
