### ISSUE TITLE
Dare dei prezzi realistici (e ingredienti) ai prodotti

### ISSUE THREAD

**Issue by jacopocav** [TecnologieWeb/progetto#46]
Non sarà mica tutto gratis, no? ;)
@luhahaha ci puoi pensare tu?

**Comment by luhahaha** [comment]
si ci penso io che chiedo anche un po in pasticceria!

**Comment by jacopocav** [comment]
Risolto da luca con ad1ec64a6405edff0938c4bbba9bd8a70143bb7e
