### ISSUE TITLE
Testare il sito su IE

### ISSUE THREAD

**Issue by jacopocav** [TecnologieWeb/progetto#48]
fino a quale versione dovremmo testare?

**Comment by jacopocav** [comment]
Questo può tornare utile: https://www.modern.ie/it-it

**Comment by Jefffrey** [comment]
Nel dubbio dalla 8 in poi.

**Comment by jacopocav** [comment]
L'ho testato su IE8 con IETester (per Windows). Ho dovuto creare un css apposito per ie8 (che non supporta alcune regole di CSS3). Resta da vedere IE9-10-11, ma non prevedo grandi problemi. IE6 e IE7 sembrano usabili, anche se il layout è abbastanza incasinato
