### ISSUE TITLE
Creazione pagina admin per gestione feedback

### ISSUE THREAD

**Issue by Jefffrey** [TecnologieWeb/progetto#5]
Pagina admin che mostra tutti i feedback non accettati e permette o di eliminarli o di accettarli.

**Comment by jacopocav** [comment]
L'admin può anche modificare i feedback o solo rimuoverli? Se può solo rimuoverli, è gia risolto con bbd022094244c9c3ac4b78009c650992d593e981

**Comment by Jefffrey** [comment]
Solo rimuoverli. Modificarli avrebbe poco senso. Sarebbe come mettere parole in bocca a qualcuno.

**Comment by jacopocav** [comment]
Ok, allora chiudo
