### ISSUE TITLE
RELAZIONE

### ISSUE THREAD

**Issue by jacopocav** [TecnologieWeb/progetto#52]
Manca da fare:
- [x] Parte su Perl (la faccio io, Jeffrey puoi fare la parte sulle api xml?)

- [x] Espandere la parte di Accessibilità e di Compatibilità

- [x] Parte su CSS (riferimento ai layout mobile e per ie8, la puoi fare tu, Luca  ?)

- [ ] Correggere tutto (per favore, seguite i consigli al capitolo 0, così si risparmia tempo)

- [x] Conversione in latex (per favore, usate i comandi latex come sono già stati usati in gran parte della relazione, per risparmiare tempo. Il resto delle conversioni le faccio io)

- [ ] Decidere chi ospiterà la copia del sito per la consegna, e modificare il link in prima pagina di conseguenza

**Comment by luhahaha** [comment]
Oggi pome appena arrivo a padova faccio tutta la parte css

**Comment by jacopocav** [comment]
@Jefffrey , non serve che tu faccia la parte xml, ho scritto io una descrizione abbastanza generica dei vari moduli. Non penso serva andare più nello specifico (se vuole la prof può leggersi i sorgenti)

**Comment by Jefffrey** [comment]
@jacopocav Non glielo consiglio, ma comunque ok. Cosa posso fare allora?

**Comment by jacopocav** [comment]
@Jefffrey magari controlla se c'è da aggiungere qualcos'altro e se ci sono errori

**Comment by luhahaha** [comment]
Io ho fatto la parte di css magari dateci una letta perchè sono un cane in italiano!:)
